
server:
  port: 3344


spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:tantaizhijun/cloud2020-config.git #配置中心的git仓库的地址
          #搜索目录
          search-paths:
            - cloud2020-config
      #读取仓库分支
      label: master


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka