#8004 表示注册到zookeeper的服务器的支付服务提供者端口号
server:
  port: 80

spring:
  application:
    #服务名称
    name: cloud-consumer-order
  cloud:
    #注册到zk的地址(zk得ip和端口),  如果是集群,....百度集群版zk
    zookeeper:
      connect-string: 192.168.1.1:2181